---
- name: Install docker and docker-compose
  hosts: aws_server
  become: yes
  tasks:
    - name: install docker
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum:
        name: docker
        state: present
    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes
    - name: Reconnet to server session
      meta: reset_connection
    - name: Make sure docker is running
      systemd:
        name: docker
        state: started
    - name: Install docker python module (for ec2 instance only)
      pip:
        name: docker

    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-{{lookup('pipe', 'uname -s')}}-{{lookup('pipe', 'uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x

- name: Start docker containers
  hosts: aws_server
  vars_files:
    - project-vars
  tasks:
    - name: Copy docker-compose file to remote_server
      copy:
        src: /home/victor/project/docker-compose.yaml
        dest: /home/ec2-user/docker-compose.yaml
    - name: Login to docker registry
      community.docker.docker_login:
        username: "{{docker_username}}"
        password: "{{docker_password}}"










# - name: Test docker pull
#   hosts: aws_server
#   tasks:
#     - name: pull redis
#         command: docker pull redis

# - name: Test docker pull
#   hosts: aws_server
#   tasks:
#     - name: pull redis
#       community.docker.docker_image:
#         name: redis
#         state: absent