---
- name: Create a namespace on k8s cluster and deploy nginx webserver
  hosts: localhost
  tasks:
    - name: Create dev namespace on cluster
      kubernetes.core.k8s:
        name: dev
        api_version: v1
        kind: Namespace
        state: present
    - name: Deploy nginx webserver
      kubernetes.core.k8s:
        src: /home/victor/project/nginx-deploy.yaml
        state: present
      