---
- name: install node and npm
  hosts: webservers
  tasks:
  - name: Update apt repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: Install nodejs and npm
    apt:
      pkg:
      - nodejs
      - npm
- name: Create new linux user for node app
  hosts: webservers
  tasks:
    - name: Create linux user
      user:
        name: vistein
        comment: Vistain Admin
        group: admin
      

- name: Deploy Nodejs app
  hosts: webservers
  become: True
  become_user: vistein
  tasks:
  - name: Unpack the nodejs file
    unarchive:
      src: /home/victor/project/react-nodejs-example/api/react-nodejs-example-1.0.0.tgz
      dest: /home/vistein/
  - name: Install dependencies
    npm:
      path:  /home/vistein/package
  - name: Start the application
    ansible.builtin.command:
      chdir: /home/vistein/package/
      cmd: node server
    async: 1000
    poll: 0
  - name: Ensure app is running
    ansible.builtin.shell: ps aux | grep node
    register: app_status
  - ansible.builtin.debug: msg={{app_status.stdout_lines}}  

      
      
