---
- name: install node and npm
  hosts: webservers
  tasks:
  - name: Update apt repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: Install nodejs and npm
    apt:
      pkg:
      - nodejs
      - npm
- name: Deploy Nodejs app
  hosts: webservers
  tasks:
  - name: Unpack the nodejs file
    unarchive:
      src: /home/victor/project/react-nodejs-example/api/react-nodejs-example-1.0.0.tgz
      dest: /root/
  - name: Install dependencies
    npm:
      path:  /root/package
  - name: Start the application
    ansible.builtin.command:
      chdir: /root/package/app
      cmd: node server



      
