---
- name: install node and npm
  hosts: webservers
  tasks:
  - name: Update apt repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: Install nodejs and npm
    apt:
      pkg:
      - nodejs
      - npm
- name: Create new linux user for node app
  hosts: webservers
  tasks:
    - name: Create linux user
      user:
        name: "{{linux_name}}"
        comment: Vistain Admin
        group: admin
      register: user_creation_result
    - debug: msg={{user_creation_result}}
      

- name: Deploy Nodejs app
  hosts: webservers
  become: True
  become_user: "{{linux_name}}"
  vars_files:
    - project-vars
  vars:
    - user_home_dir: /home/{{linux_name}}
  tasks:
  - name: Unpack the nodejs file
    unarchive:
      src: "{{location}}/api/react-nodejs-example-{{version}}.tgz"
      dest: "{{user_home_dir}}"
    register: unarchive_result
  - debug: msg={{unarchive_result}}
  - name: Install dependencies
    npm:
      path:  "{{user_home_dir}}/package"
  - name: Start the application
    ansible.builtin.command:
      chdir: "{{user_home_dir}}/package/"
      cmd: node server
    async: 1000
    poll: 0
  - name: Ensure app is running
    ansible.builtin.shell: ps aux | grep node
    register: app_status
  - ansible.builtin.debug: msg={{app_status.stdout_lines}}  

      
      
