---
- name: Install docker and docker compose
  hosts: tag_Name_Public_Server_1
  become: true
  tasks:
    - name: Create user to run playbook
      ansible.builtin.user: 
        name: ansible
        groups: adm
    - name: Install docker
      ansible.builtin.yum:
        name:
          - docker
          - python3
        state: present
    - name: Add user to docker group
      ansible.builtin.user:
        name: ansible
        groups: docker
        append: yes
    - name: Reset connection
      ansible.builtin.meta: reset_connection
    - name: Start docker process
      ansible.builtin.systemd:
        name: docker
        state: started

